app/training/forms.py
# forms.py is used to generate form fields

import re
# flask
from flask.ext.wtf import Form
from flask.ext.login import current_user
# other
from wtforms import ValidationError, StringField, IntegerField, TextAreaField, FileField, SubmitField
from wtforms.validators import Required
from datetime import datetime
from time import gmtime, strftime, localtime
# local
from ..models import CourseContent, Course

class EditCourseHTMLForm(Form):
    title = StringField('Title', validators=[Required()])
    seconds = StringField('Time')
    html = TextAreaField('')
    submit = SubmitField('Save')

class EditCourseName(Form):
    name = StringField('Name')
    submit = SubmitField('Save')

class NewCourseForm(Form):
    name = StringField('Name', validators=[Required()])
    submit = SubmitField('Create')

class NewCourseContentForm(Form):
    title = StringField('Title', validators=[Required()])
    html = TextAreaField('HTML Content', validators=[Required()])
    submit = SubmitField('Save')

class UploadImageForm(Form):
    file = FileField('File', validators=[Required()])
    submit = SubmitField('Upload')

class NewCourseImagesForm(Form):
    name = StringField('Course Name', validators=[Required()])
    file = FileField('Images', validators=[Required()])
    submit = SubmitField('Create')

app/training/__init__.py
# flask
from flask import Blueprint

training = Blueprint('training', __name__)

# local
from . import views

app/training/views.py
# views.py renders pages for creating, editing, reviewing, and approving
# expense reports.

import os, glob
from os import path

# flask
from flask.ext.login import current_user, logout_user, login_required
from flask_wtf.file import FileField
from flask import current_app, Flask, render_template, redirect, request, jsonify, url_for, flash, send_from_directory, send_file
# other
from werkzeug import secure_filename
from datetime import datetime, date
from sqlalchemy import desc, asc, and_
# local
from . import training
from .forms import EditCourseHTMLForm, NewCourseForm, NewCourseContentForm, UploadImageForm, EditCourseName, NewCourseImagesForm
from .. import db
from ..decorators import admin_required, create_required, permission_required
from ..models import User, Training, Course, CourseContent

@training.route('/', methods=['GET','POST'])
@login_required
def index():
    
    # Course
    course_id = request.args.get('cid')
    if course_id is None:
        flash("Course not found.")
        return redirect(url_for('main.dashboard'))

    course_id = int(course_id)
    course = Course.query.filter_by(id=course_id).first()
    if course is None:
        flash("Course not found.")
        return redirect(url_for('main.dashboard'))
    
    # Training
    training = Training.query.filter_by(user_id=current_user.id).filter_by(course_id=course_id).first()
    # if the location is greater than 1 and status is still 0, change status to 1 (in progress)
    if training is None:
        training = Training(user_id=current_user.id,
                            course_id=course_id,
                            year=2016,
                            status=1,
                            location=1,
                            score=0,
                            questions=0)
        db.session.add(training)
    elif training.status == 0 and training.location > 0:
        training.status = 1
        db.session.add(training)
        db.session.commit()
    
    courseContentLength = CourseContent.query.filter_by(course_id=course_id).count()
    # Location
    loc = request.args.get('loc')
    if loc is not None:
        loc = int(loc)
    elif training.location >= courseContentLength:
        loc = 1
    else:
        loc = int(training.location)
    
    course = Course.query.filter_by(id=course_id).first()

    
    # if they try to skip ahead by editing the url, set loc to their last known location
    if loc > training.location+1:
        loc = training.location
    
    if loc == training.location+1:
        training.location = loc
        db.session.add(training)
    
    # get course content for current location
    courseContent = CourseContent.query.filter_by(course_id=course_id).filter_by(location=loc).first_or_404()
    courseContentAll = CourseContent.query.filter_by(course_id=course_id).order_by(CourseContent.location).all()
    
    
    # Score
    # init scores (can prob remove)
    score=0
    questions=0
    
    # init empty scores
    if training.score is None:
        training.score = 0
    if training.questions is None:
        training.questions = 0
    if courseContent.score is None:
        courseContent.score = 0
    if courseContent.total is None:
        courseContent.total = 0
    
    if request.method == "POST":
        score = int(request.form['score'])
        questions = int(request.form['questions'])
        loc = int(request.form['loc'])
        training.location = loc
        
        if int(score) is None:
            score = 0
        if int(questions) is None:
            questions = 0
        
        training.score = int(training.score) + int(score)
        courseContent.score = int(courseContent.score) + int(score)
        training.questions = int(training.questions) + int(questions)
        courseContent.total = int(courseContent.total) + int(questions)

        db.session.add(training)
        db.session.add(courseContent)
        db.session.commit()
    # End score
    
    if loc > course.length():
        training.status = 2
        db.session.add(training)
        db.session.commit()
        flash('complete')
        return redirect(url_for('main.dashboard'))
    
    courseContent = CourseContent.query.filter_by(course_id=course_id).filter_by(location=loc).first_or_404()
    courseContentLength = CourseContent.query.filter_by(course_id=course_id).count()

    
    return render_template('training/index.html',training=training, location=loc, course=course, courseContent=courseContent, courseContentAll=courseContentAll, courseContentLength=courseContentLength)

@training.route('/test', methods=['GET','POST'])
def test():
    if request.method == "POST":
        name = request.form['name']
        
        flash(name)
        
        return redirect(url_for('main.dashboard'))


@training.route('/say_name', methods=['POST'])
def say_name():
    
    flash(request.method)
    
    json = request.get_json()
    first_name = json['first_name']
    last_name = json['last_name']
    
    flash('hi')
    # return render_template('training/test.html')
    
    return jsonify(first_name=first_name, last_name=request.method)
    
    
@training.route('/overview', methods=['GET','POST'])
@create_required
def overview():
    cid = request.args.get('cid')
    if cid is None:
        flash("Course not found.")
        return redirect(url_for('main.admin'))
    
    training = Training.query.filter_by(course_id=cid).join(User, Training.user).order_by('status').order_by('location').order_by(User.full_name).all()
    
    # present = Training.query.filter_by(course_id=cid).with_entities(Training.user_id)
    # missing = User.query.filter(~(User.id._in(present))).all()
    
    return render_template('training/overview.html', training=training, course_id=cid)


# Create new course content
@training.route('/course_content', methods=['GET','POST'])
@login_required
def course_content():
    # Course
    course_id = request.args.get('cid')
    if course_id is None:
        flash("Course not found.")
        return redirect(url_for('main.dashboard'))

    course_id = int(course_id)
    course = Course.query.filter_by(id=course_id).first()
    
    if course is None:
        flash("Course not found.")
        return redirect(url_for('main.dashboard'))
    
    courseContent = CourseContent.query.filter_by(course_id=course_id).all()
    
    # Get current location in course and increment by one
    loc=1
    
    form = NewCourseContentForm()
    if form.validate_on_submit():
        courseContent = CourseContent(course_id=course_id,
                                      title=form.title.data,
                                      location=1,
                                      html=form.html.data)
        db.session.add(courseContent)
        db.session.commit()
        return redirect(url_for('main.dashboard'))

    return render_template('training/course_content.html', form=form, course=course, courseContent=courseContent)

# Create new course content
@training.route('/contents', methods=['GET','POST'])
@login_required
def contents():
    # Course
    course_id = request.args.get('cid')
    if course_id is None:
        flash("Course not found.")
        return redirect(url_for('main.dashboard'))

    course_id = int(course_id)
    course = Course.query.filter_by(id=course_id).first()
    
    if course is None:
        flash("Course not found.")
        return redirect(url_for('main.dashboard'))
    
    courseContent = CourseContent.query.filter_by(course_id=course_id).order_by(CourseContent.location).all()
    courseContentLength = CourseContent.query.filter_by(course_id=course_id).count()
    
    # Get current location in course and increment by one
    loc=1
    
    form = NewCourseContentForm()
    if form.validate_on_submit():
        courseContent = CourseContent(course_id=course_id,
                                      title=form.title.data,
                                      location=1,
                                      html=form.html.data)
        db.session.add(courseContent)
        db.session.commit()
        return redirect(url_for('main.dashboard'))
        
    
    # should we edit the course title?

    editTitle = request.args.get('edit')
    if editTitle is not None:
        editTitle = True
    else:
        editTitle = False
    # edit course title
    editCourseName = EditCourseName()
    if editCourseName.validate_on_submit():
        course.name = editCourseName.name.data
        db.session.add(course)
        db.session.commit()
        course = Course.query.filter_by(id=course_id).first()
        return redirect(url_for('training.contents', cid=course_id))
    editCourseName.name.data = course.name
    
    return render_template('training/contents.html', form=form, course=course, courseContent=courseContent, courseContentLength=courseContentLength, editTitle=editTitle, editCourseName=editCourseName)

# Preview a course
@training.route('/edit', methods=['GET','POST'])
@login_required
def edit():
    
    # Course
    course_id = request.args.get('cid')
    if course_id is None:
        flash("Course not found.")
        return redirect(url_for('main.dashboard'))

    course_id = int(course_id)
    course = Course.query.filter_by(id=course_id).first()
    if course is None:
        flash("Course not found.")
        return redirect(url_for('main.dashboard'))
    
    # Location
    loc = request.args.get('loc')
    if loc is not None:
        loc = int(loc)
    else:
        loc = 1
    
    courseContent = CourseContent.query.filter_by(course_id=course_id).filter_by(location=loc).first_or_404()
    
    
    # Edit
    edit = request.args.get('edit')
    if edit is not None:
        edit = True
    else:
        edit = False
    
    # edit HTML code in database
    form = EditCourseHTMLForm()
    if form.validate_on_submit():
        courseContent.title = form.title.data
        

app/templates/training/add_page.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Bigelow Portal - Training{% endblock %}

{% block page_content %}

<div class="page-header">
	<h3>Create a new course</h3> 
</div>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!--                              PAGE CONTENT                             -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
{% if form %}
    {{ wtf.quick_form(form) }}
{% endif %}
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!--                            END PAGE CONTENT                           -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

{% endblock %}

app/templates/training/contents.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Bigelow Portal - Training{% endblock %}

{% block page_content %}

<div class="page-header">
	<h3>{% if editTitle %}
                {{ wtf.quick_form(editCourseName) }}
            {% else %}
                {{course.name}}  &nbsp;
                <a href="{{url_for('training.contents', cid=course.id, edit=1)}}" data-toggle="tooltip" title="Edit Name"><span class='glyphicon glyphicon-pencil' aria-hidden='true'></span></a>
            {% endif %}
          <a href="{{url_for('training.index', cid=course.id)}}" data-toggle="tooltip" title="Copy Link" class="pull-right"><span class='glyphicon glyphicon-link' aria-hidden='true'></span></a>
          
          </h3> 
</div>

<div class="panel panel-success">
    <div class="panel-heading">
        <b>Course Content</b>
        <span class='pull-right'>
            <!-- Trigger the modal with a button -->
            <a data-toggle="modal" data-target="#delete"><span class='glyphicon glyphicon-trash' aria-hidden='true'></a> &nbsp;&nbsp;

            <!-- Modal -->
            <div class="modal fade" id="delete" role="dialog">
                <div class="modal-dialog">

                  <!-- Modal content-->
                  <div class="modal-content" style='color: darkred; background-color: #FFFFFF;'>
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Are you sure you want to delete this course: <b>{{course.name}}</b>?</h4>
                    </div>
                    <div class="modal-body">
                        <p>Please type the name of the course below to confirm. Deleting this course cannot be undone.</p>
                        <b><p id='delete-course-error'></p></b>
                    </div>
                    <div class="modal-footer">
                        <input id='confirm-delete' name='confirm-delete' type="text" class='pull-left col-sm-6'></input>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-danger" onclick="delete_course()">Delete Course</button>
                        <!-- <a href="{{ url_for('training.delete_course', cid=course.id) }}" class="btn btn-danger">Delete Course</a> -->
                    </div>
                  </div>
  
                </div>
            </div>
            <a href="{{url_for('training.upload')}}" data-toggle="tooltip" title="Upload Images"><span class='glyphicon glyphicon-upload' aria-hidden='true'></span></a> &nbsp;&nbsp;
            <a href="{{url_for('training.new_page', cid=course.id)}}" data-toggle="tooltip" title="Add Page"><span class='glyphicon glyphicon-plus' aria-hidden='true'></span></a>
        </span>
    </div>
    <div class="panel-body">
        <div class='table-responsive'>
            <table class='table tablehover' style='font-size:12px;'>
                <thead>
                    <tr class='no-hover'>

                        <td style='vertical-align: bottom;' class='col-sm-1'>
                            <b>Title</b>
                        </td>

                        <td style='vertical-align: bottom;' class='col-sm-1'>
                            <b>Score</b>
                        </td>

                        <td style='vertical-align: bottom;' class='col-sm-1'>
                            <b>Timer</b>
                        </td>

                        <td style='vertical-align: bottom;' class='col-sm-1'>
                            <b>Actions</b>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    {% if courseContent %}
                    {% for course_c in courseContent %}
                    <tr class='clickable-row' data-href="{{url_for('training.edit', cid=course_c.course_id, loc=course_c.location)}}">
                        <td>
                            {{ course_c.title}}
                        </td>
                        <td>
                            {% if course_c.score %}
                                {{(course_c.score / course_c.total * 100) | round | int }}%
                            {% endif %}
                        </td>
                        <td>
                            {{ (course_c.seconds / 60) | int }}:{{ (course_c.seconds % 60) | int }}
                        </td>
                        <td>
                            {% if course_c.location != 1 %}
                                <a href="{{url_for('training.move_page', cid=course_c.course_id, loc=course_c.location, dir='up')}}"><span class='glyphicon glyphicon-triangle-top' aria-hidden='true'></span></a>&nbsp;&nbsp;
                            {% else %}
                                <span class='glyphicon glyphicon-blank' aria-hidden='true'></span>&nbsp;&nbsp;
                            {% endif %}
                            {% if course_c.location != courseContentLength %}
                                <a href="{{url_for('training.move_page', cid=course_c.course_id, loc=course_c.location, dir='down')}}"><span class='glyphicon glyphicon-triangle-bottom' aria-hidden='true'></span></a>&nbsp;&nbsp;
                            {% else %}
                                <span class='glyphicon glyphicon-blank' aria-hidden='true'></span>&nbsp;&nbsp;
                            {% endif %}
                            <a href="{{url_for('training.edit', cid=course_c.course_id, loc=course_c.location, edit=1)}}"><span class='glyphicon glyphicon-pencil' aria-hidden='true'></span></a>
                            
                        </td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>



<script type="text/javascript">
function delete_course() {
    if ( $('#confirm-delete').val() == "{{course.name}}" ){
        location.href="{{ url_for('training.delete_course', cid=course.id) }}";
    }
    else {
        $('#delete-course-error').text('Please make sure that the course name you typed matches (case sensitive) the course name: {{course.name}}');
    }
}

</script>


{% endblock %}

app/templates/training/course_from_images.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Bigelow Portal - Training{% endblock %}

{% block page_content %}

<form method="POST" enctype="multipart/form-data" class="form" role="form">
	{{ form.csrf_token }}  
    
    {{ wtf.form_field(form.name) }}
    
    {{ wtf.form_field(form.file, multiple="") }}
    
    {{ wtf.form_field(form.submit) }}

</form>

{% endblock %}

app/templates/training/files.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Bigelow Portal - Training{% endblock %}

{% block page_content %}

{{dir}} <br><br>

<ul>
{% for file in files %}
    <li>{{file}}</li>
{% endfor %}
</ul>


  

{% endblock %}

app/templates/training/new_course.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Bigelow Portal - Training{% endblock %}

{% block page_content %}

<div class="page-header">
	<h3>Create a new course</h3> 
</div>

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!--                              PAGE CONTENT                             -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
{% if form %}
    {{ wtf.quick_form(form) }}
{% endif %}
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!--                            END PAGE CONTENT                           -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

{% endblock %}

app/templates/training/overview.html
{% extends "base.html" %}

{% block title %}Bigelow Portal - Admin{% endblock %}

{% block page_content %}

<div>
  <h3>Course Info
    <a href="{{url_for('training.index', cid=course_id)}}" data-toggle="tooltip" title="View Course" class="pull-right"><span class='glyphicon glyphicon-link' aria-hidden='true'></span></a>
    <a href="{{ url_for('training.contents', cid=course_id) }}" data-toggle="tooltip" title="Edit" class='pull-right'><span class='glyphicon glyphicon-edit' aria-hidden='true'></span>&nbsp;&nbsp;</a>
  </h3>
</div>
</br>

<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <b>Training</b>
            </div>
            <div class="panel-body">
                <div class='table-responsive'>
                    <table class='table tablehover' style='font-size:12px;'>
                        <thead>
                            <tr class='no-hover'>
                                <td style='vertical-align: bottom;' class='col-sm-1 col-md-1 col-xs-1'>
                                    <b>Employee</b>
                                </td>

                                <td style='vertical-align: bottom;' class='col-sm-1 col-md-1 col-xs-1'>
                                    <b>Course</b>
                                </td>

                                <td style='vertical-align: bottom;' class='col-sm-1 col-md-1 col-xs-1'>
                                    <b>Year</b>
                                </td>

                                <td style='vertical-align: bottom;' class='col-sm-1 col-md-1 col-xs-1'>
                                    <b>Status</b>
                                </td>

                                <td style='vertical-align: bottom;' class='col-sm-1 col-md-1 col-xs-1'>
                                    <b>Location</b>
                                </td>

                                <td style='vertical-align: bottom;' class='col-sm-1 col-md-1 col-xs-1'>
                                    <b>Score</b>
                                </td>
                            </tr>
                        </thead>
                        <tbody>
                            {% if training %}
                            {% for train in training %}
                            <tr>
                                <td><a href="{{url_for('main.user', uid=train.user.id)}}">{{ train.user.full_name }}</a></td>
                                <td>{{ train.course.name }}</td>
                                <td>{{train.year}}</td>
                                <td>
                                    {% if train.status == 0 %}
                                    <span style="color:#cccccc;">NOT STARTED</span>
                                    {% elif train.status == 1 %}
                                    <span style="color:#f0ad4e;">IN PROGRESS - {{(train.location / train.course.length() * 100) | round | int }}%</span>
                                    {% elif train.status == 2 %}
                                    <span style="color:#5cb85c;">COMPLETE</span>
                                    {% elif train.status == 3 %}
                                    <span style="color:#5bc0de;">OVERRIDE</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <!-- if status is none, complete, or override -->
                                    {% if train.status == 0 or train.status == 2 or train.status == 3 %}
                                    --
                                    {% else %}
                                    {{train.location}} of {{train.course.length() }}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if train.score %}
                                        {{(train.score / train.questions * 100) | round | int }}%
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% if missing %}
  {% for user in missing %}
    {{ user.id }}
  {% endfor %}
{% endif %}

<!-- <div class='table-responsive'>
<ul>
{% for course in course_info: %}
<li><a href="{{course.url}}">{{course.name}} ({{course.updated}})</a> </li>
{% endfor %}
</ul>
</div> -->


</br></br>
{% endblock %}

app/templates/training/response.html
{% extends "base.html" %}

{% block title %}Bigelow Portal - Training{% endblock %}

{% block page_content %}

<h3>val={{val}}</h3>

<button onclick="done()" id='next'>Next</button>

<script type="text/javascript">
function done() {
  // $.post(u);
  // alert(u);
  $.ajax({
          type: 'POST',
          contentType: "application/json",
          url: 'test',
          data: { 'status' : '1' , 'message' : '2' },
          dataType: "json"
      }).done(function () {
          window.location.href = 'test';
      });
  
}
</script>

{% endblock %}

app/templates/training/test.html
<!DOCTYPE html>
<html>
    <body>
  
  <form id='sendform' method="post">
    <imput id='name' type="text"></imput>
  </form>
  
  <button id='next'>Click</button>
        
  <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
  <script type="text/javascript">
  $('#next').click(function() {
    
    $("#name").val('Kelvin');
    $("#sendform").submit();
    
  });
  </script>
    </body>
</html>

app/templates/training/upload.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Bigelow Portal - Training{% endblock %}

{% block page_content %}

<form method="POST" enctype="multipart/form-data" class="form" role="form">
	{{ form.csrf_token }}  
    
    {{ wtf.form_field(form.file, multiple="") }}
    {{ wtf.form_field(form.submit) }}

</form>

{% endblock %}